# Generated by Django 3.2.9 on 2023-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.IntegerField(null=True)),
                ('glucose', models.IntegerField(null=True)),
                ('bloodpressure', models.IntegerField(null=True)),
                ('skinthickness', models.IntegerField(null=True)),
                ('insulin', models.IntegerField(null=True)),
                ('bmi', models.IntegerField(null=True)),
                ('diabetespedigreefunction', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('outcome', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
